name: Ready for the review
on:
 pull_request:
    types: [ready_for_review]
jobs:
  check-pr-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR status
        id: pr_status
        run: |
          if [[ "${{ github.event.pull_request.draft }}" == "true" ]]; then
              echo "draft" > pr-status.txt
          else
              echo "not-draft" > pr-status.txt
          fi
      - name: Upload PR status
        uses: actions/upload-artifact@v4
        with:
          name: pr-status
          path: pr-status.txt
  trigger-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 30
      - name: Trigger e2e-dev workflow
        run: |
          echo "curl -X POST \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/version-one.yaml/dispatches \
          -d '{\"ref\":\"${{ github.head_ref }}\"}'"
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/version-one.yaml/dispatches \
          -d '{"ref":"${{ github.head_ref }}"}'
       
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          