name: clientBase v1
on:
  workflow_dispatch:
jobs:
  version1:
    name: RUN TESTS FOR V1
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [ home, login ]
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./
          spec: cypress/e2e/v-1/${{ matrix.containers }}.cy.ts
          config-file: cypress.v1.config.ts
          env: configFile=v1
        env:
          - TEST_USER_1: ${{ secrets.P_TEST_USER_1 }}
      - name: Store screenshot artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2e-screenshots
          path: ./cypress/results/
